### ISSUE TITLE
Generate SVG / PDFs (similar to wallpapers)

### ISSUE THREAD

**Issue by vilav** [mjswensen/themer-gui#11]
Would be neat to get any vector-based output (EPS, SVG, PDF) of Themer's wallpapers to incorporate into design docs / brand manuals.

**Comment by mjswensen** [comment]
Hi, @vilav, thanks for the comment. The current version of Themer exports the wallpaper files in SVG format already—are you requesting additional vector formats?

**Comment by vilav** [comment]
hey @mjswensen! Apologies, didn't look at it close enough, have the file extensions hidden on this. And thank you for building Themer, Matt.

**Comment by mjswensen** [comment]
No worries, @vilav ! And you are welcome, thank YOU for using it!
