### ISSUE TITLE
open colors.js

### ISSUE THREAD

**Issue by therealplato** [mjswensen/themer-gui#13]
Given I `Export Colors & Themes`
I expect to be able to import those colors next time I run Themer to tweak them
But actually I have to recreate my theme because I didn't save a `.thmr` file

**Comment by mjswensen** [comment]
Good call, @therealplato , it would be nice to have an "Import Colors..." option.

**Comment by mjswensen** [comment]
@therealplato , I've decided to deprecate this Electron-based application in favor of a Progressive Web App located at [themer.mjswensen.com](https://themer.mjswensen.com), and one of the nice new features is that all theme data is stored in the URL. I, too, found that working with `.thmr` files was problematic, or at least inconvenient, so now saving themes is as easy as bookmarking a URL in your browser. 👍
