### ISSUE TITLE
Add support for installation via package managers

### ISSUE THREAD

**Issue by tassyguy** [mjswensen/themer-gui#15]
A lot of macOS developers I know use Homebrew to manage their applications, and I feel adding support for installation via a package manager for the GUI version of the application could help users out a lot, especially those that use a CLI to update/install dependencies and apps. In addition, Themer's CLI counterpart already uses npm as an installation option so I feel it would make sense to offer the same feature to those that prefer the GUI version.

For specific package managers, I feel adding support for these ones, in particular, would be best:

- macOS: Homebrew (Cask), MacPorts
- Linux: dpkg, pacman, apt-get, Linuxbrew
- Windows: NuGet, Chocolatey, Cygwin

Some of these may have already been implemented without my knowledge but if not I personally own a Mac so I'm more than happy to assist with adding to Homebrew as a Cask, and I can look into how to add the app to Chocolatey since I use that on my Windows partition.

**Comment by mjswensen** [comment]
Hi @tassyguy , I've actually decided to deprecate this Electron-based application in favor of a Progressive Web App, located at [themer.mjswensen.com](https://themer.mjswensen.com); with ease of installation and distribution—as you've helped highlight here—being one of the primary motivators for the change. Thanks for taking the time to file this issue!
