### ISSUE TITLE
Support Chrome theme

### ISSUE THREAD

**Issue by adamlaz** [mjswensen/themer-gui#5]
example starter: https://github.com/greenido/Chrome-Base-Theme-Sample 

Chrome themes are great for businesses/orgs that use gSuite. Can be a quick way to get some internal branding happening.

**Comment by mjswensen** [comment]
Great idea! Thanks @adamlaz

**Comment by mjswensen** [comment]
@adamlaz , I just released [version 0.6.0](https://github.com/mjswensen/themer-gui/releases/tag/v0.6.0), which adds support for generating Chrome themes. 👍 See that release page for more details.

<img width="452" alt="themer chrome export option" src="https://user-images.githubusercontent.com/1591879/30644517-d6582e60-9dcf-11e7-827a-07625f8de340.png">

On Windows or Mac, open the Themer app and it will download the update in the background, and alert you when the update is ready to install. For Linux, you can download the updated version from the releases page.
