### ISSUE TITLE
Steps for building on Linux

### ISSUE THREAD

**Issue by citrusui** [mjswensen/themer-gui#6]
*A tiny bit of work is required, but building Themer for Linux\* isn't too hard.*

**Prerequisites:**

- `npm i --save 7zip-bin-linux`

- `sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils`

Then, run `npm run dist`...

![screenshot from 2017-08-26 20 10 16](https://user-images.githubusercontent.com/9056756/29746031-9f3f8c90-8a9a-11e7-8f0b-9050a910b25f.png)

...and you should see Themer running on Linux!

*\* Only tested on Ubuntu 16.04 LTS. It shouldn't be too difficult to compile for other distributions.*

**Comment by mjswensen** [comment]
Thank you so much for your research on this! I am working on getting a build for linux set up through CI so that users can download a pre-built package, but I will add a link to this issue in the README in the meantime. 👍
