### ISSUE TITLE
Support for BBEdit export

### ISSUE THREAD

**Issue by gvkempen** [mjswensen/themer-gui#7]
Many folks (myself included) still use BBEdit but no easy to use theme editor supports it. It would be awesome if Themer would be able to generate BBEdit color schemes.

**Comment by mjswensen** [comment]
Thanks, @gvkempen . I don't think a BBEdit theme would be too hard. I've got it on my backlog.

**Comment by mjswensen** [comment]
@gvkempen , I've added support for BBEdit, see [release v0.8.0](https://github.com/mjswensen/themer-gui/releases/tag/v0.8.0). (If you open up Themer on your Mac it will automatically download the update in the background and alert you when the update is ready to be applied.)

**Comment by gvkempen** [comment]
Awesome, thanks for the addition!
