### ISSUE TITLE
ConEmu support for Windows

### ISSUE THREAD

**Issue by brianjking** [mjswensen/themer-gui#8]

**Comment by mjswensen** [comment]
Thanks, @brianjking ! I've got ConEmu on my backlog.

**Comment by mjswensen** [comment]
@brianjking , I've added ConEmu support in [release v0.9.0](https://github.com/mjswensen/themer-gui/releases/tag/v0.9.0). (If you open up Themer on your Windows machine, the update will download automatically in the background and Themer will alert you when the update is ready to install.) Refer to the [themer-conemu package readme](https://github.com/mjswensen/themer-conemu#installation--usage) for how to install the outputted ConEmu theme. 👍
